// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svkmahihzzfwlbeebfwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2a21haGloenpmd2xiZWViZndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MjI2MTIsImV4cCI6MjA3OTQ5ODYxMn0.mt3u7iYGlkwAWt13OBUmtZTNwQpZf0gYLiksX0dmdBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});